/* soapJHServiceSoapService.h
   Generated by gSOAP 2.8.51 for JHService.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapJHServiceSoapService_H
#define soapJHServiceSoapService_H
#include "soapH.h"

    class SOAP_CMAC JHServiceSoapService : public soap {
      public:
        /// Variables globally declared in JHService.h, if any
        /// Construct a service with new managing context
        JHServiceSoapService();
        /// Copy constructor
        JHServiceSoapService(const JHServiceSoapService&);
        /// Construct service given a managing context
        JHServiceSoapService(const struct soap&);
        /// Constructor taking input+output mode flags for the new managing context
        JHServiceSoapService(soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        JHServiceSoapService(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and managing context
        virtual ~JHServiceSoapService();
        /// Delete all deserialized data (with soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to defaults
        virtual void reset();
        /// Initializer used by constructors
        virtual void JHServiceSoapService_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual JHServiceSoapService *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        JHServiceSoapService& operator=(const JHServiceSoapService&);
        /// Close connection (normally automatic)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Return sender-related fault to sender
        virtual int soap_senderfault(const char *string, const char *detailXML);
        /// Return sender-related fault with SOAP 1.2 subcode to sender
        virtual int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Return receiver-related fault to sender
        virtual int soap_receiverfault(const char *string, const char *detailXML);
        /// Return receiver-related fault with SOAP 1.2 subcode to sender
        virtual int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
    #ifndef WITH_NOIO
        /// Run simple single-thread (iterative, non-SSL) service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int run(int port);
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// Run simple single-thread SSL service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int ssl_run(int port);
    #endif
        /// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
        virtual SOAP_SOCKET bind(const char *host, int port, int backlog);
        /// Accept next request (returns socket or SOAP_INVALID_SOCKET)
        virtual SOAP_SOCKET accept();
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// When SSL is used, after accept() should perform and accept SSL handshake
        virtual int ssl_accept();
    #endif
    #endif
        /// After accept() serve this request (returns SOAP_OK or error code)
        virtual int serve();
        /// Used by serve() to dispatch a request (returns SOAP_OK or error code)
        virtual int dispatch();
        ///
        /// Service operations are listed below (you should define these)
        /// Note: compile with -DWITH_PURE_VIRTUAL for pure virtual methods
        ///
        /// Web service operation 'test' (returns SOAP_OK or error code)
        virtual int test(_tempuri__test *tempuri__test, _tempuri__testResponse &tempuri__testResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'ToolingTimes' (returns SOAP_OK or error code)
        virtual int ToolingTimes(_tempuri__ToolingTimes *tempuri__ToolingTimes, _tempuri__ToolingTimesResponse &tempuri__ToolingTimesResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'BillState' (returns SOAP_OK or error code)
        virtual int BillState(_tempuri__BillState *tempuri__BillState, _tempuri__BillStateResponse &tempuri__BillStateResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'LineInventory' (returns SOAP_OK or error code)
        virtual int LineInventory(_tempuri__LineInventory *tempuri__LineInventory, _tempuri__LineInventoryResponse &tempuri__LineInventoryResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'AnDonStart' (returns SOAP_OK or error code)
        virtual int AnDonStart(_tempuri__AnDonStart *tempuri__AnDonStart, _tempuri__AnDonStartResponse &tempuri__AnDonStartResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'AnDonList' (returns SOAP_OK or error code)
        virtual int AnDonList(_tempuri__AnDonList *tempuri__AnDonList, _tempuri__AnDonListResponse &tempuri__AnDonListResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'AnDonOver' (returns SOAP_OK or error code)
        virtual int AnDonOver(_tempuri__AnDonOver *tempuri__AnDonOver, _tempuri__AnDonOverResponse &tempuri__AnDonOverResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'DocAdd' (returns SOAP_OK or error code)
        virtual int DocAdd(_tempuri__DocAdd *tempuri__DocAdd, _tempuri__DocAddResponse &tempuri__DocAddResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'test' (returns SOAP_OK or error code)
        virtual int test_(_tempuri__test *tempuri__test, _tempuri__testResponse &tempuri__testResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'ToolingTimes' (returns SOAP_OK or error code)
        virtual int ToolingTimes_(_tempuri__ToolingTimes *tempuri__ToolingTimes, _tempuri__ToolingTimesResponse &tempuri__ToolingTimesResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'BillState' (returns SOAP_OK or error code)
        virtual int BillState_(_tempuri__BillState *tempuri__BillState, _tempuri__BillStateResponse &tempuri__BillStateResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'LineInventory' (returns SOAP_OK or error code)
        virtual int LineInventory_(_tempuri__LineInventory *tempuri__LineInventory, _tempuri__LineInventoryResponse &tempuri__LineInventoryResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'AnDonStart' (returns SOAP_OK or error code)
        virtual int AnDonStart_(_tempuri__AnDonStart *tempuri__AnDonStart, _tempuri__AnDonStartResponse &tempuri__AnDonStartResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'AnDonList' (returns SOAP_OK or error code)
        virtual int AnDonList_(_tempuri__AnDonList *tempuri__AnDonList, _tempuri__AnDonListResponse &tempuri__AnDonListResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'AnDonOver' (returns SOAP_OK or error code)
        virtual int AnDonOver_(_tempuri__AnDonOver *tempuri__AnDonOver, _tempuri__AnDonOverResponse &tempuri__AnDonOverResponse) SOAP_PURE_VIRTUAL;
        /// Web service operation 'DocAdd' (returns SOAP_OK or error code)
        virtual int DocAdd_(_tempuri__DocAdd *tempuri__DocAdd, _tempuri__DocAddResponse &tempuri__DocAddResponse) SOAP_PURE_VIRTUAL;
    };
#endif
